# Generated by Django 4.0 on 2022-01-10 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_winner_item_remove_winner_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='start_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
    ]
